# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster
RUN pip install requests

EXPOSE 80

ADD Python/* .

ENV GOOGLE_MAP_JS_API_KEY -
ENV GOOGLE_GEOCODE_API_KEY -



#WORKDIR /var/CarPoolMashup

#COPY requirements.txt requirements.txt
#RUN pip3 install -r requirements.txt

#COPY ../Python/* .

CMD [ "python3", "main.py", "80"]
